---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nubase
  annotations:
    description: |
      NuBase - A Couchbase powered Developer-friendly database, built for WASMCON 2024
spec:
  components:
    - name: nubase
      type: component
      properties:
        image: file://./build/nubase_s.wasm
      traits:
        # We allow our DB to scale up as needed to handle incoming load
        - type: spreadscaler
          properties:
            instances: 100
        # Link the component to the wasmcloud couchbase provider
        - type: link
          properties:
            namespace: wasmcloud
            package: couchbase
            interfaces: [document]
            target:
              name: couchbase
              config:
                - name: provider-config
                  properties:
                    connectionString: 'localhost'
                    username: 'Administrator'
                    bucketName: 'nubase'
                    # NOTE: Do not put passwords in your link config in production!
                    # wasmCloud has secrets support (https://wasmcloud.com/docs/concepts/secrets).
                    #
                    # We do this here only to make demoing simpler, and this only works on a
                    # limited build (-wasmcon2024) of the provider
                    allow_unsafe_password: 'enabled'
                    password: 'password'

    # This proivder mediates our access to Couchbase
    - name: couchbase
      type: capability
      properties:
        #image: ghcr.io/vados-cosmonic/provider-wasmcloud-couchbase:v0.1.0-wamscon2024
        image: file:///home/mrman/code/work/cosmonic/forks/wasmcloud-provider-couchbase/build/wasmcloud-provider-couchbase.par.gz
        id: couchbase

    # This provider enables us to receive HTTP requests
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.2
      traits:
        - type: link
          properties:
            target: nubase
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
