image: laurentdoguin/workspace-couchbase-wash@sha256:1ea93a23a591303279aef90f0fc0343c9a85ad801438d00c58fcea8cab3aa895

# Commands that will run on workspace start
tasks:
  - name: Start Couchbase Server
    command: |
      sudo /entrypoint.sh couchbase-server
  - name: Start Wash
    command: |
      gp await-port 8091
      wash up

vscode:
    extensions:
        - couchbase.vscode-couchbase
        - golang.go

# exposed ports
ports:
- port: 4222 # LocalNats
  onOpen: ignore
- port: 4223 # Nats Websocket
  onOpen: ignore
- port: 8080 # Application HTTP Server provider default endpoint (see wadm.yaml)
  onOpen: open-browser
- port: 8091 # Couchbase Web console, REST/HTTP interface
  onOpen: open-browser
  visibility: public
- port: 8092 # Views, queries, XDCR
  onOpen: ignore
- port: 8093 # Query services (4.0+)
  onOpen: ignore
- port: 8094 # Full-text Search (4.5+)
  onOpen: ignore
- port: 8095 # Analytics (5.5+)
  onOpen: ignore
- port: 8096 # Eventing (5.5+)
  onOpen: ignore
- port: 11207 # Smart client library data node access (SSL)
  onOpen: ignore
- port: 11210 # Smart client library/moxi data node access
  onOpen: ignore
- port: 11211 # Legacy non-smart client library data node access
  onOpen: ignore
- port: 18091 # Couchbase Web console, REST/HTTP interface (SSL)
  onOpen: ignore
- port: 18092 # Views, query, XDCR (SSL)
  onOpen: ignore
- port: 18093 # Query services (SSL) (4.0+)
  onOpen: ignore
- port: 18094 # Full-text Search (SSL) (4.5+)
  onOpen: ignore
- port: 18095 # Analytics (SSL) (5.5+)
  onOpen: ignore
- port: 18096 # Eventing (SSL) (5.5+)
  onOpen: ignore
