
x-common-variables: &common-variables
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=nukv
      - COUCHBASE_CONNECTION_STRING=localhost

services:
  couchbase:
    image: couchbase:7.6.3@sha256:78446fa1cf1c9cea6c563114b7882b5c3f84d1663207b15dd966bf8f10b427c0
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
      - 11207:11207
      - 11211:11211
    environment: *common-variables
    volumes:
      - couchbase-data:/opt/couchbase/var

  couchbase-init:
    image: couchbase:latest
    depends_on:
      - couchbase
    environment: *common-variables
    volumes:
      - ./init-couchbase.sh:/init-couchbase.sh
    entrypoint: '/init-couchbase.sh'


  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.58
    restart: always
    ports:
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
      - '4317:4317'
      - '4318:4318'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      COLLECTOR_OTLP_ENABLED: 'true'

volumes:
  couchbase-data:
