package kubecon2024:workshop@0.1.0;

/// NuBase is a WebAssembly native database, implemented in WebAssembly
///
/// NuBase aims to implement a subset of Couchbase features which is even simpler
/// for developers to use, from WebAssembly environments, and even in browsers.
///
/// A component that implements this world *is* the NuBase database.
///
world nubase {
  /// This include pulls in interfaces and WIT that enable easy building of
  /// WebAssembly components in Go (TinyGo)
  include wasmcloud:component-go/imports@0.1.0;

  /// Import wasi:keyvalue functionality, which lets us access KV storage.
  ///
  /// While wasi:keyvalue is generic,  fully featured `wasmcloud:couchbase` is
  /// available in `wasmcloud-provider-couchbase`
  ///
  /// If you'd like to see what an enterprise-grade WIT representing the other interfaces
  /// (ex. document, query, etc) of Couchbase looks like, see the link below:
  ///
  /// https://github.com/couchbaselabs/wasmcloud-provider-couchbase/blob/main/wit/couchbase/document.wit
  ///
  import wrpc:keyvalue/store@0.2.0-draft;
  import wrpc:keyvalue/atomics@0.2.0-draft;

  /// Exposes a HTTP handler that delivers the NuBase API
  export wasi:http/incoming-handler@0.2.0;
}
