package kubecon2024:workshop;

/// NuDB is a simplified HTTP API-driven database, powered by Couchbase, implemented in WebAssembly
///
/// NuDB aims to be simple for developers to use by exposing an extremely simple HTTP API, but
/// powerful by making use of native Couchbase primitives.
world nudb {
  /// This include pulls in interfaces and WIT that enable easy building of 
  /// WebAssembly components in Go (TinyGo)
  include wasmcloud:component-go/imports@0.1.0;

  /// Makes available native Couchbase functionality  
  import wasmcloud:couchbase/document@0.1.0-draft;

  /// Exposes a HTTP handler that delivers the NuDB API
  export wasi:http/incoming-handler@0.2.0;
}
