---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nubase
  annotations:
    description: |
      NuBase - A Couchbase powered Developer-friendly database, built for WASMCON 2024
spec:
  components:
    - name: nubase
      type: component
      properties:
        image: file://./build/nubase_s.wasm
      traits:
        # We allow our DB to scale up as needed to handle incoming load
        - type: spreadscaler
          properties:
            instances: 100
        # Link the component to the provider on wasi-keyvalue
        - type: link
          properties:
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target:
              name: couchbase
              secrets:
                - name: password
                  properties:
                    policy: nats-kv
                    key: couchbase_password
              config:
                - name: provider-config
                  properties:
                    connectionString: 'localhost'
                    username: 'admin'
                    bucketName: 'test'

    # This proivder mediates our access to couchbase
    - name: couchbase
      type: capability
      properties:
        image: ghcr.io/vados-cosmonic/provider-wasmcloud-couchbase:v0.1.0

    # This provider enables us to receive HTTP requests
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.2
      traits:
        - type: link
          properties:
            target: nubase
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
